/**
 * One search across the archive and the research network.
 *
 * TWO MODES OVER ONE INDEX
 *
 * The plan asks for "Separate Knowledge and Research search modes while sharing one underlying
 * index". They are separate because the two audiences want different things from the same word: a
 * reader searching "Ohafia" in Knowledge mode wants the histories, the clan and the photographs, and
 * a researcher searching it in Research mode wants the papers written about it. They share the index
 * because a word is a word — two indexes would be two answers to "what does this archive hold".
 *
 * MODE IS A FILTER, NOT A SECOND QUERY PATH
 *
 * `mode` narrows which kinds are searched. It does not change how anything is ranked or matched, so
 * there is one implementation to get right rather than two that drift.
 *
 * DIACRITICS, AND WHY THE QUERY IS FOLDED TOO
 *
 * Migration 0041 gives every searchable name a `folded_*` column, generated by Postgres. The QUERY
 * has to be folded the same way before it is compared, or a reader who types the diacritics gets no
 * results while one who omits them does — the worst possible behaviour for the diaspora reader the
 * brief names first. The fold is done with the dictionary's own `toSearchForm`, so `@ozituma/core`
 * decides what "the same word" means and both sites agree.
 *
 * WHAT A RESULT IS
 *
 * Every result is a typed, addressable record with a canonical URL, because the plan requires that
 * results link to canonical entity pages and that the archive provide stable, crawlable URLs. A
 * result that cannot be linked to is not a search result, it is a match.
 */
import { toSearchForm } from '@ozituma/core';
import type { Db } from '@ozituma/db/client';

export type SearchKind = 'article' | 'entity' | 'publication' | 'source' | 'media' | 'label' | 'researcher';
export type SearchMode = 'knowledge' | 'research';

/** Which kinds each mode covers. One list, so a new kind is added in one place. */
export const MODE_KINDS: Record<SearchMode, SearchKind[]> = {
  knowledge: ['article', 'entity', 'label', 'media', 'source'],
  research: ['publication', 'researcher'],
};

export const KIND_LABEL: Record<SearchKind, string> = {
  article: 'History', entity: 'Entity', publication: 'Research', source: 'Source',
  media: 'Photograph or record', label: 'Subject', researcher: 'Researcher',
};

export interface SearchResult {
  kind: SearchKind;
  id: number;
  title: string;
  /** A sentence of context: a standfirst, an entity summary, an author list. */
  detail: string | null;
  url: string;
  /** Where the match happened, shown to the reader so a result is explicable. */
  matchedOn: 'title' | 'body' | 'alias' | 'subject' | 'author';
  /** Higher is better. Only comparable within one query. */
  rank: number;
}

export interface SearchOptions {
  mode?: SearchMode;
  /** Narrow to one or more kinds. Defaults to everything the mode covers. */
  kinds?: SearchKind[];
  limit?: number;
  offset?: number;
  /** Filter by discipline, for research results. */
  discipline?: string | null;
  /**
   * Whether records held by agreement are searchable by this caller.
   *
   * `access_tier = 'by_agreement'` means the record cannot be read at all without an institutional access
   * agreement (migration 0057). **A search result is part of reading a record**: it carries the record's own
   * title and its standfirst, and it hands the reader the address. So a caller who does not hold
   * `read_restricted` is not shown those results, and a caller who does hold it is — which is why this is an
   * option rather than a permanent `where` clause. The caller is the page, which knows who is signed in;
   * **the default is false, because the safe state has to be the default state.**
   *
   * This is NOT the media register's `restricted`, which means an item may be read here and may not be
   * republished, and does not affect search at all.
   */
  includeByAgreement?: boolean;
}

export interface SearchOutcome {
  query: string;
  mode: SearchMode;
  results: SearchResult[];
  /** What each kind contributed, so a facet rail can show real counts rather than guesses. */
  counts: Record<SearchKind, number>;
  /** What was searched, stated so the page can be honest about the scope. */
  searched: SearchKind[];
}

/**
 * The fold, from the dictionary.
 *
 * `toSearchForm` handles more than a lowercase call: it tidies, folds tone and dotted vowels, and
 * strips spacing marks, which is exactly what the generated columns do in SQL. Using the same
 * function here is what keeps the two sides of the comparison identical.
 */
export function foldQuery(query: string): string {
  return toSearchForm(query).toLowerCase().trim();
}

export async function searchEverything(
  db: Db,
  query: string,
  options: SearchOptions = {}
): Promise<SearchOutcome> {
  const mode = options.mode ?? 'knowledge';
  const raw = query.trim();
  const folded = foldQuery(raw);
  const kinds = options.kinds && options.kinds.length > 0 ? options.kinds : MODE_KINDS[mode];

  const outcome: SearchOutcome = {
    query: raw,
    mode,
    results: [],
    counts: { article: 0, entity: 0, publication: 0, source: 0, media: 0, label: 0, researcher: 0 },
    searched: kinds,
  };

  // Nothing to search for. Returning early is not an optimisation: an empty query that matched
  // everything would be a search page that leaks the whole archive into one response.
  if (folded.length === 0) return outcome;

  const limit = Math.min(Math.max(options.limit ?? 20, 1), 100);
  const pattern = `%${folded}%`;
  const prefix = `${folded}%`;

  const perKind: Partial<Record<SearchKind, SearchResult[]>> = {};

  if (kinds.includes('article')) {
    const rows = await db.rows<Record<string, unknown>>(
      `select a.id, a.slug, a.title, a.standfirst, c.display_name as author,
              (a.folded_title like $2) as in_title
         from ozikoro_article a
         left join ozikoro_contributor c on c.id = a.author_id
        where a.status = 'published' and a.is_page = false
          and (a.access_tier = 'open' or $5::boolean)
          and (a.folded_title like $1
               or a.search_vector @@ websearch_to_tsquery('english', $3)
               or c.display_name ilike $1)
        order by (a.folded_title like $2) desc, a.published_at desc nulls last
        limit $4`,
      [pattern, prefix, raw, limit, Boolean(options.includeByAgreement)]
    );
    perKind.article = rows.map((r) => ({
      kind: 'article' as const,
      id: Number(r.id),
      title: String(r.title ?? '').trim() || 'Untitled record',
      detail: r.standfirst ? String(r.standfirst).slice(0, 180) : (r.author ? `By ${String(r.author)}` : null),
      url: `/${String(r.slug)}/`,
      matchedOn: r.in_title ? 'title' : (r.author ? 'author' : 'body'),
      rank: r.in_title ? 3 : 1,
    }));
  }

  if (kinds.includes('entity')) {
    const rows = await db.rows<Record<string, unknown>>(
      `select id, slug, name, kind, summary,
              (folded_name like $2) as in_name,
              exists (select 1 from unnest(aliases) al where lower(regexp_replace(normalize(al, NFD), '[\\u0300-\\u036f]', '', 'g')) like $1) as in_alias
         from ozikoro_entity
        where folded_name like $1
           or exists (select 1 from unnest(aliases) al where lower(regexp_replace(normalize(al, NFD), '[\\u0300-\\u036f]', '', 'g')) like $1)
        order by (folded_name like $2) desc, name
        limit $3`,
      [pattern, prefix, limit]
    );
    perKind.entity = rows.map((r) => ({
      kind: 'entity' as const,
      id: Number(r.id),
      title: String(r.name),
      detail: r.summary ? String(r.summary).slice(0, 180) : String(r.kind).replace(/_/g, ' '),
      url: `/entities/${String(r.slug)}/`,
      matchedOn: r.in_alias && !r.in_name ? 'alias' : 'title',
      rank: r.in_name ? 3 : 2,
    }));
  }

  if (kinds.includes('label')) {
    const rows = await db.rows<Record<string, unknown>>(
      `select l.slug, l.name,
              (select count(*)::int from ozikoro_article_label al where al.label_id = l.id) as uses
         from ozikoro_label l
        where l.folded_name like $1
        order by uses desc, l.name
        limit $2`,
      [pattern, limit]
    );
    perKind.label = rows.map((r) => ({
      kind: 'label' as const,
      id: 0,
      title: String(r.name),
      detail: `${Number(r.uses)} ${Number(r.uses) === 1 ? 'record' : 'records'} filed under this subject`,
      url: `/labels/${String(r.slug)}/`,
      matchedOn: 'subject',
      rank: 2,
    }));
  }

  if (kinds.includes('media')) {
    const rows = await db.rows<Record<string, unknown>>(
      `select m.id, m.slug, m.title, m.kind, m.alt_text,
              (select count(*)::int from ozikoro_article_media am where am.media_id = m.id) as uses
         from ozikoro_media m
        where m.title ilike $1 or m.alt_text ilike $1 or m.caption ilike $1
        order by uses desc, m.id
        limit $2`,
      [pattern, limit]
    );
    const letter = (k: string) => (k === 'image' ? 'P' : k === 'video' ? 'V' : k === 'audio' ? 'A' : k === 'document' ? 'D' : 'X');
    perKind.media = rows.map((r) => ({
      kind: 'media' as const,
      id: Number(r.id),
      title: String(r.title ?? '').trim() || 'Untitled item',
      detail: `OZ-${letter(String(r.kind))}-${String(r.id).padStart(4, '0')} · used on ${Number(r.uses)} ${Number(r.uses) === 1 ? 'record' : 'records'}`,
      url: `/documents/${String(r.slug)}/`,
      matchedOn: 'title',
      rank: 1,
    }));
  }

  if (kinds.includes('source')) {
    const rows = await db.rows<Record<string, unknown>>(
      `select id, slug, title, kind, year, authors
         from ozikoro_source
        where title ilike $1 or exists (select 1 from unnest(authors) a where a ilike $1)
        order by year desc nulls last, title
        limit $2`,
      [pattern, limit]
    );
    perKind.source = rows.map((r) => ({
      kind: 'source' as const,
      id: Number(r.id),
      title: String(r.title),
      detail: [
        Array.isArray(r.authors) && r.authors.length > 0 ? r.authors.map(String).join(', ') : null,
        r.year === null || r.year === undefined ? null : String(r.year),
        String(r.kind).replace(/_/g, ' '),
      ].filter(Boolean).join(' · '),
      url: `/sources/${String(r.slug)}/`,
      matchedOn: 'title',
      rank: 1,
    }));
  }

  if (kinds.includes('publication')) {
    const params: unknown[] = [pattern, prefix, raw, limit];
    let disciplineClause = '';
    if (options.discipline) {
      params.push(options.discipline);
      disciplineClause = ` and $5 = any(p.disciplines)`;
    }
    const rows = await db.rows<Record<string, unknown>>(
      `select p.id, p.slug, p.title, p.abstract, p.kind, p.peer_reviewed, p.published_at,
              (p.folded_title like $2) as in_title,
              (select string_agg(pa.name, ', ' order by pa.position) from ozikoro_publication_author pa where pa.publication_id = p.id) as authors
         from ozikoro_publication p
        where p.status = 'published' and p.is_public = true
          and (p.folded_title like $1
               or p.search_vector @@ websearch_to_tsquery('english', $3)
               or exists (select 1 from ozikoro_publication_author pa where pa.publication_id = p.id and pa.name ilike $1))
          ${disciplineClause}
        order by (p.folded_title like $2) desc, p.published_at desc nulls last
        limit $4`,
      params
    );
    perKind.publication = rows.map((r) => ({
      kind: 'publication' as const,
      id: Number(r.id),
      title: String(r.title),
      detail: [r.authors ? String(r.authors) : null, r.peer_reviewed ? 'peer-reviewed' : 'editorially reviewed only']
        .filter(Boolean).join(' · '),
      url: `/publications/${String(r.slug)}/`,
      matchedOn: r.in_title ? 'title' : 'body',
      rank: r.in_title ? 3 : 1,
    }));
  }

  if (kinds.includes('researcher')) {
    const rows = await db.rows<Record<string, unknown>>(
      `select m.account_id, coalesce(m.display_name, a.display_name, a.email) as name,
              m.headline, m.institution, m.research_interests,
              (select count(*)::int from ozikoro_publication p
                 join ozikoro_publication_author pa on pa.publication_id = p.id
                where pa.account_id = m.account_id and p.status = 'published' and p.is_public = true) as pubs
         from ozikoro_member m join account a on a.id = m.account_id
        where m.is_public = true and m.status = 'active'
          and (lower(regexp_replace(normalize(coalesce(m.display_name, a.display_name, a.email), NFD), '[\\u0300-\\u036f]', '', 'g')) like $1
               or exists (select 1 from unnest(m.research_interests) i where lower(regexp_replace(normalize(i, NFD), '[\\u0300-\\u036f]', '', 'g')) like $1)
               or lower(m.institution) like $1)
        order by pubs desc, name
        limit $2`,
      [pattern, limit]
    );
    perKind.researcher = rows.map((r) => ({
      kind: 'researcher' as const,
      id: Number(r.account_id),
      title: String(r.name),
      detail: [
        r.headline ? String(r.headline) : (r.institution ? String(r.institution) : 'Independent researcher'),
        `${Number(r.pubs)} ${Number(r.pubs) === 1 ? 'publication' : 'publications'}`,
      ].join(' · '),
      url: `/researchers/${Number(r.account_id)}/`,
      matchedOn: 'title',
      rank: 1,
    }));
  }

  // Merge, rank, and count. Interleaved rather than grouped by kind, because a reader searching a
  // word wants the best answer first, not the best history followed by the best paper.
  const merged: SearchResult[] = [];
  for (const kind of kinds) merged.push(...(perKind[kind] ?? []));
  merged.sort((a, b) => b.rank - a.rank || a.title.localeCompare(b.title));

  for (const result of merged) outcome.counts[result.kind] += 1;

  const offset = Math.max(options.offset ?? 0, 0);
  outcome.results = merged.slice(offset, offset + limit);
  return outcome;
}
