#!/usr/bin/env node
/**
 * Build the Igbo lexicon the TTS service reads — from the work that already measured it.
 *
 * WHAT THIS DOES, AND WHY IT IS A BUILD STEP RATHER THAN A QUERY
 *
 * `packages/ozikoro/src/pronunciation.ts` knows how to read Ozituma: it builds the dictionary index, it
 * knows which headwords are clean words rather than strings, it knows the English collisions, and it knows
 * the dissection rule. **All of that was measured against the live cluster before it was written**, and
 * re-deriving any of it here would be a second, worse copy.
 *
 * So this script runs that code **once**, with the cluster available, and snapshots what it produces into
 * `apps/media/lexicon/igbo-lexicon.json`. The service then loads the file and rebuilds the same index with
 * no database at all — because a PGlite cluster is single-process and has been corrupted seven times in a
 * single day, and putting one on the path of every audio request would be a choice to make that eight.
 *
 * **The snapshot is not committed.** The owner's rule is that the dictionary lookup must query ozituma
 * rather than read a list, *"a list would be stale within a week"* — so the file is derived data, kept out
 * of git, and regenerated by this command. What IS committed is the command and the coverage it prints.
 *
 * THE PROOF IT CARRIES
 *
 * `WordIndex.segment` is a closure inside `buildDictionaryIndex` and cannot be serialised, so the service
 * transcribes its rule. A transcription that drifts is exactly the defect this repository keeps recording,
 * so this script **rebuilds the index from the bytes it is about to write and compares it against the live
 * one** — every published search form for `has`, every archive word for `segment` — and refuses to write
 * if they disagree. The proof runs here, against the real dictionary, and its result is printed.
 *
 * Usage:
 *   npm -w @ozikoro/media run lexicon
 *   node scripts/build-lexicon.ts --out /tmp/x.json --articles 0     # skip the archive scan
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { buildDictionaryIndex, findIgboWords, toSpokenScript } from '@ozikoro/platform';
/**
 * The real `Db`, imported as a TYPE only. The runtime import below is dynamic, so `@ozituma/db` is never
 * loaded by the service — but the type has to be the genuine article. A hand-written structural stand-in
 * for `Db` was the first version and it did not typecheck, **which is the correct outcome**: a local
 * lookalike would silently accept a call shape the real client does not have.
 */
import type { Db } from '@ozituma/db/client';
import { lexiconPath, piecesFromForms, rebuildWordIndex, type LexiconFile } from '../lib/lexicon.ts';


function arg(name: string, fallback: string | null = null): string | null {
  const index = process.argv.indexOf(`--${name}`);
  if (index === -1) return fallback;
  const next = process.argv[index + 1];
  return next && !next.startsWith('--') ? next : 'true';
}

function flag(name: string): boolean {
  return process.argv.includes(`--${name}`);
}

function say(line = ''): void {
  process.stdout.write(`${line}\n`);
}

const CLEAN_FORM = `search_form ~ '^[a-zŋ]+$' and length(search_form) >= 2`;

async function main(): Promise<number> {
  const out = arg('out') ?? lexiconPath();
  // `-1` means every published record; `0` means skip the scan. The scan is the default because the
  // coverage figure it produces is the honest answer to "does this actually help?", and a build step whose
  // most useful number is off by default is a build step whose most useful number is never seen.
  const articleLimit = Number(arg('articles', '-1') ?? '-1');

  say('Building the Igbo lexicon for the media service.');
  say(`  cluster: ${process.env.OZITUMA_DB_PATH ?? '(default .data/pg)'}`);
  say(`  output:  ${out}`);
  say();

  const { createDb } = (await import('@ozituma/db/client')) as unknown as {
    createDb: () => Promise<Db>;
  };
  const db: Db = await createDb();

  // -------------------------------------------------------------------------
  // 1. What the dictionary actually holds, counted rather than asserted.
  // -------------------------------------------------------------------------
  const index = await buildDictionaryIndex(db);

  const totals = await db.one<{
    published: number;
    with_pronunciation: number;
    with_syllables: number;
    recordings: number;
    dialect_rows: number;
    dialect_pronunciations: number;
  }>(
    `select
       (select count(*) from word where language_code='ibo' and status='published')::int as published,
       (select count(*) from word where language_code='ibo' and status='published' and pronunciation is not null)::int as with_pronunciation,
       (select count(*) from word where language_code='ibo' and status='published' and syllables is not null)::int as with_syllables,
       (select count(*) from audio a join word w on w.id = a.word_id where w.language_code='ibo')::int as recordings,
       (select count(*) from word_dialect wd join word w on w.id=wd.word_id where w.language_code='ibo')::int as dialect_rows,
       (select count(*) from word_dialect wd join word w on w.id=wd.word_id where w.language_code='ibo' and wd.pronunciation is not null)::int as dialect_pronunciations`
  );

  if (!totals) throw new Error('the dictionary could not be counted; nothing was written');

  say('The dictionary, measured now:');
  say(`  published Igbo words                 ${totals.published}`);
  say(`  with a written pronunciation         ${totals.with_pronunciation}`);
  say(`  with a syllable breakdown            ${totals.with_syllables}`);
  say(`  pronunciation RECORDINGS (audio)     ${totals.recordings}`);
  say(`  dialect spellings                    ${totals.dialect_rows}`);
  say(`  dialect spellings with respelling    ${totals.dialect_pronunciations}`);
  say(`  clean single-token folded forms      ${index.counts.forms}`);
  say(`  clean multi-word headwords           ${index.counts.phrases}`);
  say(`  English collisions                   ${index.counts.collisions}`);
  say();

  // -------------------------------------------------------------------------
  // 2. The headwords, with their spellings and whatever sound the dictionary has.
  // -------------------------------------------------------------------------
  const dialectByWord = new Map<number, { code: string | null; respelling: string | null }>();
  const dialectRows = await db.rows<{ word_id: number; code: string | null; pronunciation: string | null }>(
    `select wd.word_id, d.code, wd.pronunciation
       from word_dialect wd
       join word w on w.id = wd.word_id
       left join dialect d on d.id = wd.dialect_id
      where w.language_code = 'ibo'`
  );
  for (const row of dialectRows) {
    const seen = dialectByWord.get(row.word_id);
    // A respelling is worth more than a dialect code, so it wins when both are present.
    if (!seen || (!seen.respelling && row.pronunciation)) {
      dialectByWord.set(row.word_id, { code: row.code ?? null, respelling: row.pronunciation ?? null });
    }
  }

  const wordRows = await db.rows<{
    id: number;
    headword: string;
    search_form: string;
    pronunciation: string | null;
    syllables: string | null;
  }>(
    `select id, headword, search_form, pronunciation, syllables
       from word
      where language_code = 'ibo' and status = 'published' and ${CLEAN_FORM}`
  );

  const words: LexiconFile['words'] = wordRows.map((row) => {
    const dialect = dialectByWord.get(row.id);
    return {
      folded: row.search_form,
      headword: row.headword,
      // The word's own respelling first, then a dialect one. Both measured; usually both are null.
      respelling: row.pronunciation ?? dialect?.respelling ?? null,
      syllables: row.syllables,
      dialectCode: dialect?.code ?? null,
      wordId: row.id,
      audioUrl: null,
    };
  });

  // -------------------------------------------------------------------------
  // 3. The archive's own words — the measurement the owner was given.
  // -------------------------------------------------------------------------
  const archive = {
    distinctIgboWords: 0,
    namedByDictionary: 0,
    rescuedByDissection: 0,
    unsayable: 0,
    measuredOn: new Date().toISOString(),
  };

  if (articleLimit !== 0) {
    const allArticles = await db.rows<{ slug: string; body_html: string | null }>(
      `select slug, body_html from ozikoro_article
        where status = 'published' and is_page = false and body_html is not null
        order by slug`
    );
    const articles = articleLimit > 0 ? allArticles.slice(0, articleLimit) : allArticles;
    say(`Scanning ${articles.length} published records for their Igbo words ...`);

    const occurrences = new Map<string, { surface: string; count: number }>();
    /** The same count under the opposite policy, so the two can be told apart rather than argued about. */
    const withAmbiguous = new Set<string>();
    let characters = 0;
    let scanned = 0;

    for (const article of articles) {
      const { script } = toSpokenScript(article.body_html ?? '');
      characters += script.length;
      const found = findIgboWords(script, index);
      for (const word of found.igbo) {
        const seen = occurrences.get(word.folded);
        if (seen) seen.count += word.count;
        else occurrences.set(word.folded, { surface: word.surface, count: word.count });
      }
      /*
       * THE SAME PASS, UNDER THE OTHER POLICY.
       *
       * `findIgboWords` excludes Igbo headwords that are also ordinary English words unless
       * `includeAmbiguous` is set, and the two policies give different totals for the archive. An earlier
       * round recorded **2,368** distinct Igbo words; this run's default policy counts 1,751. The gap is
       * very close to the number of English-collision headwords in the text, **so both are printed here**
       * rather than one being asserted — a coverage claim that changes with an unstated flag is the kind of
       * number this project keeps having to correct.
       */
      for (const word of findIgboWords(script, index, { includeAmbiguous: true }).igbo) {
        withAmbiguous.add(word.folded);
      }
      scanned += 1;
      if (scanned % 250 === 0) say(`  ... ${scanned}/${articles.length}`);
    }

    archive.distinctIgboWords = occurrences.size;
    for (const folded of occurrences.keys()) {
      if (index.has(folded)) archive.namedByDictionary += 1;
      else if (index.segment(folded)) archive.rescuedByDissection += 1;
      else archive.unsayable += 1;
    }
    say();
    say(`  distinct including English collisions   ${withAmbiguous.size}  (the other policy — see the note)`);

    say();
    say('The archive, measured now:');
    say(`  records scanned                      ${articles.length}`);
    say(`  spoken script characters             ${characters.toLocaleString('en-GB')}`);
    say(`  distinct Igbo words                  ${archive.distinctIgboWords}`);
    say(`  named by the dictionary              ${archive.namedByDictionary}`);
    say(`  rescued by dissection                ${archive.rescuedByDissection}`);
    say(`  GENUINELY UNSAYABLE                  ${archive.unsayable}`);
    say();

    // Every archive word gets a lexicon entry, even when the dictionary does not name it, so the service
    // can report the miss by name rather than by count.
    const have = new Set(words.map((w) => w.folded));
    for (const [folded, seen] of occurrences) {
      if (have.has(folded)) continue;
      words.push({
        folded,
        headword: seen.surface,
        respelling: null,
        syllables: null,
        dialectCode: null,
        wordId: null,
        audioUrl: null,
      });
      have.add(folded);
    }
  } else {
    say('Archive scan skipped (--articles 0).');
    say();
  }

  // -------------------------------------------------------------------------
  // 4. Assemble, then PROVE the rebuild, then write.
  // -------------------------------------------------------------------------
  const lexicon: LexiconFile = {
    version: 1,
    generatedAt: new Date().toISOString(),
    source: {
      publishedIgboWords: totals.published,
      cleanFoldedForms: index.counts.forms,
      cleanMultiWordHeadwords: index.counts.phrases,
      englishCollisions: index.counts.collisions,
      respellings: totals.with_pronunciation + totals.dialect_pronunciations,
      recordings: totals.recordings,
      syllables: totals.with_syllables,
    },
    archive,
    forms: [...index.forms].sort(),
    phrases: [...index.phrases.entries()].sort((a, b) => a[0].localeCompare(b[0])),
    words: words.sort((a, b) => a.folded.localeCompare(b.folded)),
    pieces: piecesFromForms(index.forms),
    collisions: [...index.forms].filter((f) => index.isEnglishCollision(f)).sort(),
  };

  const rebuilt = rebuildWordIndex(lexicon);

  // `has` over every published search form, clean or not — the ones the SQL filter drops must be dropped
  // by the rebuild too, which is the part a naive `new Set(forms)` would get wrong.
  const everyForm = await db.rows<{ search_form: string }>(
    `select distinct search_form from word where language_code='ibo' and status='published'`
  );
  let hasChecked = 0;
  let hasMismatch = 0;
  for (const row of everyForm) {
    hasChecked += 1;
    if (index.has(row.search_form) !== rebuilt.has(row.search_form)) {
      hasMismatch += 1;
      if (hasMismatch <= 5) say(`  HAS MISMATCH: ${JSON.stringify(row.search_form)}`);
    }
  }

  let segChecked = 0;
  let segMismatch = 0;
  for (const word of lexicon.words) {
    segChecked += 1;
    const live = index.segment(word.folded);
    const copy = rebuilt.segment(word.folded);
    if (JSON.stringify(live) !== JSON.stringify(copy)) {
      segMismatch += 1;
      if (segMismatch <= 5) {
        say(`  SEGMENT MISMATCH: ${JSON.stringify(word.folded)} live=${JSON.stringify(live)} rebuilt=${JSON.stringify(copy)}`);
      }
    }
  }

  say('Proving the rebuild matches the live index:');
  say(`  has()      checked ${hasChecked}, mismatched ${hasMismatch}`);
  say(`  segment()  checked ${segChecked}, mismatched ${segMismatch}`);

  if (hasMismatch > 0 || segMismatch > 0) {
    say();
    say('REFUSING TO WRITE: the rebuilt index does not match the one built from the dictionary.');
    say('The transcription of `segment` in apps/media/lib/lexicon.ts has drifted from');
    say('packages/ozikoro/src/pronunciation.ts. Fix the transcription, not this check.');
    await db.close();
    return 1;
  }
  say('  the rebuild is identical. Writing.');
  say();

  if (!existsSync(dirname(out))) mkdirSync(dirname(out), { recursive: true });
  const json = JSON.stringify(lexicon);
  writeFileSync(out, json);

  const mb = (Buffer.byteLength(json) / 1_048_576).toFixed(1);
  say(`Wrote ${out}`);
  say(`  ${mb} MB, ${lexicon.forms.length} forms, ${lexicon.phrases.length} phrases, ${lexicon.words.length} words`);
  say(`  ${lexicon.pieces.length} dissection pieces`);
  say();
  say(join('Archive coverage: ', ''));
  say(`  ${archive.distinctIgboWords} distinct Igbo words; ${archive.namedByDictionary} named, ` +
      `${archive.rescuedByDissection} rescued by dissection, ${archive.unsayable} unsayable.`);

  await db.close();
  return 0;
}

main().then(
  (code) => process.exit(code),
  (error: unknown) => {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`\nbuild-lexicon failed: ${message}\n`);
    process.exit(1);
  }
);
