// Ndebe reference data gathered from ndebe.org and typendebe.com.
// Glyph output stays in prototype notation until the licensed font and verified mapping are connected.

/**
 * Ńdẹ́bẹ́ script data.
 *
 * The stems and vowels below are the REAL ones, from typendebe.com's own `input-data.js`. The file
 * previously held a hand-written approximation whose glyph parts were labelled with bracket notation
 * because no verified mapping existed — it does now, and it is in `ndebe-input-data.ts`. These two
 * exports are kept at their original names so the studio's imports did not have to change.
 */
export const ndebeCredit = "Ńdẹ́bẹ́ is a modern writing system for the Ìgbò language, invented in 2009 by Lotanna Igwe-Odunze.";

/** Every real combined glyph, keyed "consonant|vowel|tone". */
export const ndebeCombined: Record<string, string> = {
  "nw|a|enu": "\u{e500}",
  "nw|a|ntela": "\u{e501}",
  "nw|a|ani": "\u{e502}",
  "gb|a|enu": "\u{e51b}",
  "gb|a|ntela": "\u{e51c}",
  "gb|a|ani": "\u{e51d}",
  "kp|a|enu": "\u{e536}",
  "kp|a|ntela": "\u{e537}",
  "kp|a|ani": "\u{e538}",
  "b|a|enu": "\u{e551}",
  "b|a|ntela": "\u{e552}",
  "b|a|ani": "\u{e553}",
  "p|a|enu": "\u{e56c}",
  "p|a|ntela": "\u{e56d}",
  "p|a|ani": "\u{e56e}",
  "ny|a|enu": "\u{e587}",
  "ny|a|ntela": "\u{e588}",
  "ny|a|ani": "\u{e589}",
  "m|a|enu": "\u{e5a2}",
  "m|a|ntela": "\u{e5a3}",
  "m|a|ani": "\u{e5a4}",
  "gv|a|enu": "\u{e5bd}",
  "gv|a|ntela": "\u{e5be}",
  "gv|a|ani": "\u{e5bf}",
  "g|a|enu": "\u{e5d9}",
  "g|a|ntela": "\u{e5da}",
  "g|a|ani": "\u{e5db}",
  "nly|a|enu": "\u{e5f4}",
  "nly|a|ntela": "\u{e5f5}",
  "nly|a|ani": "\u{e5f6}",
  "gw|a|enu": "\u{e60f}",
  "gw|a|ntela": "\u{e610}",
  "gw|a|ani": "\u{e611}",
  "k|a|enu": "\u{e62a}",
  "k|a|ntela": "\u{e62b}",
  "k|a|ani": "\u{e62c}",
  "kw|a|enu": "\u{e645}",
  "kw|a|ntela": "\u{e646}",
  "kw|a|ani": "\u{e647}",
  "n|a|enu": "\u{e660}",
  "n|a|ntela": "\u{e661}",
  "n|a|ani": "\u{e662}",
  "rh|a|enu": "\u{e67b}",
  "rh|a|ntela": "\u{e67c}",
  "rh|a|ani": "\u{e67d}",
  "d|a|enu": "\u{e696}",
  "d|a|ntela": "\u{e697}",
  "d|a|ani": "\u{e698}",
  "lr|a|enu": "\u{e6b1}",
  "lr|a|ntela": "\u{e6b2}",
  "lr|a|ani": "\u{e6b3}",
  "yh|a|enu": "\u{e6cc}",
  "yh|a|ntela": "\u{e6cd}",
  "yh|a|ani": "\u{e6ce}",
  "r|a|enu": "\u{e6e7}",
  "r|a|ntela": "\u{e6e8}",
  "r|a|ani": "\u{e6e9}",
  "y|a|enu": "\u{e702}",
  "y|a|ntela": "\u{e703}",
  "y|a|ani": "\u{e704}",
  "l|a|enu": "\u{e71d}",
  "l|a|ntela": "\u{e71e}",
  "l|a|ani": "\u{e71f}",
  "fhsh|a|enu": "\u{e738}",
  "fhsh|a|ntela": "\u{e739}",
  "fhsh|a|ani": "\u{e73a}",
  "ch|a|enu": "\u{e753}",
  "ch|a|ntela": "\u{e754}",
  "ch|a|ani": "\u{e755}",
  "rsh|a|enu": "\u{e76e}",
  "rsh|a|ntela": "\u{e76f}",
  "rsh|a|ani": "\u{e770}",
  "jz|a|enu": "\u{e789}",
  "jz|a|ntela": "\u{e78a}",
  "jz|a|ani": "\u{e78b}",
  "ssh|a|enu": "\u{e7a4}",
  "ssh|a|ntela": "\u{e7a5}",
  "ssh|a|ani": "\u{e7a6}",
  "j|a|enu": "\u{e7bf}",
  "j|a|ntela": "\u{e7c0}",
  "j|a|ani": "\u{e7c1}",
  "bv|a|enu": "\u{e7da}",
  "bv|a|ntela": "\u{e7db}",
  "bv|a|ani": "\u{e7dc}",
  "s|a|enu": "\u{e7f5}",
  "s|a|ntela": "\u{e7f6}",
  "s|a|ani": "\u{e7f7}",
  "t|a|enu": "\u{e810}",
  "t|a|ntela": "\u{e811}",
  "t|a|ani": "\u{e812}",
  "fp|a|enu": "\u{e82b}",
  "fp|a|ntela": "\u{e82c}",
  "fp|a|ani": "\u{e82d}",
  "f|a|enu": "\u{e846}",
  "f|a|ntela": "\u{e847}",
  "f|a|ani": "\u{e848}",
  "z|a|enu": "\u{e861}",
  "z|a|ntela": "\u{e862}",
  "z|a|ani": "\u{e863}",
  "bw|a|enu": "\u{e87c}",
  "bw|a|ntela": "\u{e87d}",
  "bw|a|ani": "\u{e87e}",
  "st|a|enu": "\u{e897}",
  "st|a|ntela": "\u{e898}",
  "st|a|ani": "\u{e899}",
  "fv|a|enu": "\u{e8b2}",
  "fv|a|ntela": "\u{e8b3}",
  "fv|a|ani": "\u{e8b4}",
  "ygh|a|enu": "\u{e8cd}",
  "ygh|a|ntela": "\u{e8ce}",
  "ygh|a|ani": "\u{e8cf}",
  "rf|a|enu": "\u{e8e8}",
  "rf|a|ntela": "\u{e8e9}",
  "rf|a|ani": "\u{e8ea}",
  "w|a|enu": "\u{e903}",
  "w|a|ntela": "\u{e904}",
  "w|a|ani": "\u{e905}",
  "wgh|a|enu": "\u{e91e}",
  "wgh|a|ntela": "\u{e91f}",
  "wgh|a|ani": "\u{e920}",
  "nyn|a|enu": "\u{e939}",
  "nyn|a|ntela": "\u{e93a}",
  "nyn|a|ani": "\u{e93b}",
  "nwn|a|enu": "\u{e954}",
  "nwn|a|ntela": "\u{e955}",
  "nwn|a|ani": "\u{e956}",
  "nw|e|enu": "\u{e50f}",
  "nw|e|ntela": "\u{e510}",
  "nw|e|ani": "\u{e511}",
  "gb|e|enu": "\u{e52a}",
  "gb|e|ntela": "\u{e52b}",
  "gb|e|ani": "\u{e52c}",
  "kp|e|enu": "\u{e545}",
  "kp|e|ntela": "\u{e546}",
  "kp|e|ani": "\u{e547}",
  "b|e|enu": "\u{e560}",
  "b|e|ntela": "\u{e561}",
  "b|e|ani": "\u{e562}",
  "p|e|enu": "\u{e57b}",
  "p|e|ntela": "\u{e57c}",
  "p|e|ani": "\u{e57d}",
  "ny|e|enu": "\u{e596}",
  "ny|e|ntela": "\u{e597}",
  "ny|e|ani": "\u{e598}",
  "m|e|enu": "\u{e5b1}",
  "m|e|ntela": "\u{e5b2}",
  "m|e|ani": "\u{e5b3}",
  "gv|e|enu": "\u{e5cd}",
  "gv|e|ntela": "\u{e5ce}",
  "gv|e|ani": "\u{e5cf}",
  "g|e|enu": "\u{e5e8}",
  "g|e|ntela": "\u{e5e9}",
  "g|e|ani": "\u{e5ea}",
  "nly|e|enu": "\u{e603}",
  "nly|e|ntela": "\u{e604}",
  "nly|e|ani": "\u{e605}",
  "gw|e|enu": "\u{e61e}",
  "gw|e|ntela": "\u{e61f}",
  "gw|e|ani": "\u{e620}",
  "k|e|enu": "\u{e639}",
  "k|e|ntela": "\u{e63a}",
  "k|e|ani": "\u{e63b}",
  "kw|e|enu": "\u{e654}",
  "kw|e|ntela": "\u{e655}",
  "kw|e|ani": "\u{e656}",
  "n|e|enu": "\u{e66f}",
  "n|e|ntela": "\u{e670}",
  "n|e|ani": "\u{e671}",
  "rh|e|enu": "\u{e68a}",
  "rh|e|ntela": "\u{e68b}",
  "rh|e|ani": "\u{e68c}",
  "d|e|enu": "\u{e6a5}",
  "d|e|ntela": "\u{e6a6}",
  "d|e|ani": "\u{e6a7}",
  "lr|e|enu": "\u{e6c0}",
  "lr|e|ntela": "\u{e6c1}",
  "lr|e|ani": "\u{e6c2}",
  "yh|e|enu": "\u{e6db}",
  "yh|e|ntela": "\u{e6dc}",
  "yh|e|ani": "\u{e6dd}",
  "r|e|enu": "\u{e6f6}",
  "r|e|ntela": "\u{e6f7}",
  "r|e|ani": "\u{e6f8}",
  "y|e|enu": "\u{e711}",
  "y|e|ntela": "\u{e712}",
  "y|e|ani": "\u{e713}",
  "l|e|enu": "\u{e72c}",
  "l|e|ntela": "\u{e72d}",
  "l|e|ani": "\u{e72e}",
  "fhsh|e|enu": "\u{e747}",
  "fhsh|e|ntela": "\u{e748}",
  "fhsh|e|ani": "\u{e749}",
  "ch|e|enu": "\u{e762}",
  "ch|e|ntela": "\u{e763}",
  "ch|e|ani": "\u{e764}",
  "rsh|e|enu": "\u{e77d}",
  "rsh|e|ntela": "\u{e77e}",
  "rsh|e|ani": "\u{e77f}",
  "jz|e|enu": "\u{e798}",
  "jz|e|ntela": "\u{e799}",
  "jz|e|ani": "\u{e79a}",
  "ssh|e|enu": "\u{e7b3}",
  "ssh|e|ntela": "\u{e7b4}",
  "ssh|e|ani": "\u{e7b5}",
  "j|e|enu": "\u{e7ce}",
  "j|e|ntela": "\u{e7cf}",
  "j|e|ani": "\u{e7d0}",
  "bv|e|enu": "\u{e7e9}",
  "bv|e|ntela": "\u{e7ea}",
  "bv|e|ani": "\u{e7eb}",
  "s|e|enu": "\u{e804}",
  "s|e|ntela": "\u{e805}",
  "s|e|ani": "\u{e806}",
  "t|e|enu": "\u{e81f}",
  "t|e|ntela": "\u{e820}",
  "t|e|ani": "\u{e821}",
  "fp|e|enu": "\u{e83a}",
  "fp|e|ntela": "\u{e83b}",
  "fp|e|ani": "\u{e83c}",
  "f|e|enu": "\u{e855}",
  "f|e|ntela": "\u{e856}",
  "f|e|ani": "\u{e857}",
  "z|e|enu": "\u{e870}",
  "z|e|ntela": "\u{e871}",
  "z|e|ani": "\u{e872}",
  "bw|e|enu": "\u{e88b}",
  "bw|e|ntela": "\u{e88c}",
  "bw|e|ani": "\u{e88d}",
  "st|e|enu": "\u{e8a6}",
  "st|e|ntela": "\u{e8a7}",
  "st|e|ani": "\u{e8a8}",
  "fv|e|enu": "\u{e8c1}",
  "fv|e|ntela": "\u{e8c2}",
  "fv|e|ani": "\u{e8c3}",
  "ygh|e|enu": "\u{e8dc}",
  "ygh|e|ntela": "\u{e8dd}",
  "ygh|e|ani": "\u{e8de}",
  "rf|e|enu": "\u{e8f7}",
  "rf|e|ntela": "\u{e8f8}",
  "rf|e|ani": "\u{e8f9}",
  "w|e|enu": "\u{e912}",
  "w|e|ntela": "\u{e913}",
  "w|e|ani": "\u{e914}",
  "wgh|e|enu": "\u{e92d}",
  "wgh|e|ntela": "\u{e92e}",
  "wgh|e|ani": "\u{e92f}",
  "nyn|e|enu": "\u{e948}",
  "nyn|e|ntela": "\u{e949}",
  "nyn|e|ani": "\u{e94a}",
  "nwn|e|enu": "\u{e963}",
  "nwn|e|ntela": "\u{e964}",
  "nwn|e|ani": "\u{e965}",
  "nw|i|enu": "\u{e512}",
  "nw|i|ntela": "\u{e513}",
  "nw|i|ani": "\u{e514}",
  "gb|i|enu": "\u{e52d}",
  "gb|i|ntela": "\u{e52e}",
  "gb|i|ani": "\u{e52f}",
  "kp|i|enu": "\u{e548}",
  "kp|i|ntela": "\u{e549}",
  "kp|i|ani": "\u{e54a}",
  "b|i|enu": "\u{e563}",
  "b|i|ntela": "\u{e564}",
  "b|i|ani": "\u{e565}",
  "p|i|enu": "\u{e57e}",
  "p|i|ntela": "\u{e57f}",
  "p|i|ani": "\u{e580}",
  "ny|i|enu": "\u{e599}",
  "ny|i|ntela": "\u{e59a}",
  "ny|i|ani": "\u{e59b}",
  "m|i|enu": "\u{e5b4}",
  "m|i|ntela": "\u{e5b5}",
  "m|i|ani": "\u{e5b6}",
  "gv|i|enu": "\u{e5d0}",
  "gv|i|ntela": "\u{e5d1}",
  "gv|i|ani": "\u{e5d2}",
  "g|i|enu": "\u{e5eb}",
  "g|i|ntela": "\u{e5ec}",
  "g|i|ani": "\u{e5ed}",
  "nly|i|enu": "\u{e606}",
  "nly|i|ntela": "\u{e607}",
  "nly|i|ani": "\u{e608}",
  "gw|i|enu": "\u{e621}",
  "gw|i|ntela": "\u{e622}",
  "gw|i|ani": "\u{e623}",
  "k|i|enu": "\u{e63c}",
  "k|i|ntela": "\u{e63d}",
  "k|i|ani": "\u{e63e}",
  "kw|i|enu": "\u{e657}",
  "kw|i|ntela": "\u{e658}",
  "kw|i|ani": "\u{e659}",
  "n|i|enu": "\u{e672}",
  "n|i|ntela": "\u{e673}",
  "n|i|ani": "\u{e674}",
  "rh|i|enu": "\u{e68d}",
  "rh|i|ntela": "\u{e68e}",
  "rh|i|ani": "\u{e68f}",
  "d|i|enu": "\u{e6a8}",
  "d|i|ntela": "\u{e6a9}",
  "d|i|ani": "\u{e6aa}",
  "lr|i|enu": "\u{e6c3}",
  "lr|i|ntela": "\u{e6c4}",
  "lr|i|ani": "\u{e6c5}",
  "yh|i|enu": "\u{e6de}",
  "yh|i|ntela": "\u{e6df}",
  "yh|i|ani": "\u{e6e0}",
  "r|i|enu": "\u{e6f9}",
  "r|i|ntela": "\u{e6fa}",
  "r|i|ani": "\u{e6fb}",
  "y|i|enu": "\u{e714}",
  "y|i|ntela": "\u{e715}",
  "y|i|ani": "\u{e716}",
  "l|i|enu": "\u{e72f}",
  "l|i|ntela": "\u{e730}",
  "l|i|ani": "\u{e731}",
  "fhsh|i|enu": "\u{e74a}",
  "fhsh|i|ntela": "\u{e74b}",
  "fhsh|i|ani": "\u{e74c}",
  "ch|i|enu": "\u{e765}",
  "ch|i|ntela": "\u{e766}",
  "ch|i|ani": "\u{e767}",
  "rsh|i|enu": "\u{e780}",
  "rsh|i|ntela": "\u{e781}",
  "rsh|i|ani": "\u{e782}",
  "jz|i|enu": "\u{e79b}",
  "jz|i|ntela": "\u{e79c}",
  "jz|i|ani": "\u{e79d}",
  "ssh|i|enu": "\u{e7b6}",
  "ssh|i|ntela": "\u{e7b7}",
  "ssh|i|ani": "\u{e7b8}",
  "j|i|enu": "\u{e7d1}",
  "j|i|ntela": "\u{e7d2}",
  "j|i|ani": "\u{e7d3}",
  "bv|i|enu": "\u{e7ec}",
  "bv|i|ntela": "\u{e7ed}",
  "bv|i|ani": "\u{e7ee}",
  "s|i|enu": "\u{e807}",
  "s|i|ntela": "\u{e808}",
  "s|i|ani": "\u{e809}",
  "t|i|enu": "\u{e822}",
  "t|i|ntela": "\u{e823}",
  "t|i|ani": "\u{e824}",
  "fp|i|enu": "\u{e83d}",
  "fp|i|ntela": "\u{e83e}",
  "fp|i|ani": "\u{e83f}",
  "f|i|enu": "\u{e858}",
  "f|i|ntela": "\u{e859}",
  "f|i|ani": "\u{e85a}",
  "z|i|enu": "\u{e873}",
  "z|i|ntela": "\u{e874}",
  "z|i|ani": "\u{e875}",
  "bw|i|enu": "\u{e88e}",
  "bw|i|ntela": "\u{e88f}",
  "bw|i|ani": "\u{e890}",
  "st|i|enu": "\u{e8a9}",
  "st|i|ntela": "\u{e8aa}",
  "st|i|ani": "\u{e8ab}",
  "fv|i|enu": "\u{e8c4}",
  "fv|i|ntela": "\u{e8c5}",
  "fv|i|ani": "\u{e8c6}",
  "ygh|i|enu": "\u{e8df}",
  "ygh|i|ntela": "\u{e8e0}",
  "ygh|i|ani": "\u{e8e1}",
  "rf|i|enu": "\u{e8fa}",
  "rf|i|ntela": "\u{e8fb}",
  "rf|i|ani": "\u{e8fc}",
  "w|i|enu": "\u{e915}",
  "w|i|ntela": "\u{e916}",
  "w|i|ani": "\u{e917}",
  "wgh|i|enu": "\u{e930}",
  "wgh|i|ntela": "\u{e931}",
  "wgh|i|ani": "\u{e932}",
  "nyn|i|enu": "\u{e94b}",
  "nyn|i|ntela": "\u{e94c}",
  "nyn|i|ani": "\u{e94d}",
  "nwn|i|enu": "\u{e966}",
  "nwn|i|ntela": "\u{e967}",
  "nwn|i|ani": "\u{e968}",
  "nw|o|enu": "\u{e515}",
  "nw|o|ntela": "\u{e516}",
  "nw|o|ani": "\u{e517}",
  "gb|o|enu": "\u{e530}",
  "gb|o|ntela": "\u{e531}",
  "gb|o|ani": "\u{e532}",
  "kp|o|enu": "\u{e54b}",
  "kp|o|ntela": "\u{e54c}",
  "kp|o|ani": "\u{e54d}",
  "b|o|enu": "\u{e566}",
  "b|o|ntela": "\u{e567}",
  "b|o|ani": "\u{e568}",
  "p|o|enu": "\u{e581}",
  "p|o|ntela": "\u{e582}",
  "p|o|ani": "\u{e583}",
  "ny|o|enu": "\u{e59c}",
  "ny|o|ntela": "\u{e59d}",
  "ny|o|ani": "\u{e59e}",
  "m|o|enu": "\u{e5b7}",
  "m|o|ntela": "\u{e5b8}",
  "m|o|ani": "\u{e5b9}",
  "gv|o|enu": "\u{e5d3}",
  "gv|o|ntela": "\u{e5d4}",
  "gv|o|ani": "\u{e5d5}",
  "g|o|enu": "\u{e5ee}",
  "g|o|ntela": "\u{e5ef}",
  "g|o|ani": "\u{e5f0}",
  "nly|o|enu": "\u{e609}",
  "nly|o|ntela": "\u{e60a}",
  "nly|o|ani": "\u{e60b}",
  "gw|o|enu": "\u{e624}",
  "gw|o|ntela": "\u{e625}",
  "gw|o|ani": "\u{e626}",
  "k|o|enu": "\u{e63f}",
  "k|o|ntela": "\u{e640}",
  "k|o|ani": "\u{e641}",
  "kw|o|enu": "\u{e65a}",
  "kw|o|ntela": "\u{e65b}",
  "kw|o|ani": "\u{e65c}",
  "n|o|enu": "\u{e675}",
  "n|o|ntela": "\u{e676}",
  "n|o|ani": "\u{e677}",
  "rh|o|enu": "\u{e690}",
  "rh|o|ntela": "\u{e691}",
  "rh|o|ani": "\u{e692}",
  "d|o|enu": "\u{e6ab}",
  "d|o|ntela": "\u{e6ac}",
  "d|o|ani": "\u{e6ad}",
  "lr|o|enu": "\u{e6c6}",
  "lr|o|ntela": "\u{e6c7}",
  "lr|o|ani": "\u{e6c8}",
  "yh|o|enu": "\u{e6e1}",
  "yh|o|ntela": "\u{e6e2}",
  "yh|o|ani": "\u{e6e3}",
  "r|o|enu": "\u{e6fc}",
  "r|o|ntela": "\u{e6fd}",
  "r|o|ani": "\u{e6fe}",
  "y|o|enu": "\u{e717}",
  "y|o|ntela": "\u{e718}",
  "y|o|ani": "\u{e719}",
  "l|o|enu": "\u{e732}",
  "l|o|ntela": "\u{e733}",
  "l|o|ani": "\u{e734}",
  "fhsh|o|enu": "\u{e74d}",
  "fhsh|o|ntela": "\u{e74e}",
  "fhsh|o|ani": "\u{e74f}",
  "ch|o|enu": "\u{e768}",
  "ch|o|ntela": "\u{e769}",
  "ch|o|ani": "\u{e76a}",
  "rsh|o|enu": "\u{e783}",
  "rsh|o|ntela": "\u{e784}",
  "rsh|o|ani": "\u{e785}",
  "jz|o|enu": "\u{e79e}",
  "jz|o|ntela": "\u{e79f}",
  "jz|o|ani": "\u{e7a0}",
  "ssh|o|enu": "\u{e7b9}",
  "ssh|o|ntela": "\u{e7ba}",
  "ssh|o|ani": "\u{e7bb}",
  "j|o|enu": "\u{e7d4}",
  "j|o|ntela": "\u{e7d5}",
  "j|o|ani": "\u{e7d6}",
  "bv|o|enu": "\u{e7ef}",
  "bv|o|ntela": "\u{e7f0}",
  "bv|o|ani": "\u{e7f1}",
  "s|o|enu": "\u{e80a}",
  "s|o|ntela": "\u{e80b}",
  "s|o|ani": "\u{e80c}",
  "t|o|enu": "\u{e825}",
  "t|o|ntela": "\u{e826}",
  "t|o|ani": "\u{e827}",
  "fp|o|enu": "\u{e840}",
  "fp|o|ntela": "\u{e841}",
  "fp|o|ani": "\u{e842}",
  "f|o|enu": "\u{e85b}",
  "f|o|ntela": "\u{e85c}",
  "f|o|ani": "\u{e85d}",
  "z|o|enu": "\u{e876}",
  "z|o|ntela": "\u{e877}",
  "z|o|ani": "\u{e878}",
  "bw|o|enu": "\u{e891}",
  "bw|o|ntela": "\u{e892}",
  "bw|o|ani": "\u{e893}",
  "st|o|enu": "\u{e8ac}",
  "st|o|ntela": "\u{e8ad}",
  "st|o|ani": "\u{e8ae}",
  "fv|o|enu": "\u{e8c7}",
  "fv|o|ntela": "\u{e8c8}",
  "fv|o|ani": "\u{e8c9}",
  "ygh|o|enu": "\u{e8e2}",
  "ygh|o|ntela": "\u{e8e3}",
  "ygh|o|ani": "\u{e8e4}",
  "rf|o|enu": "\u{e8fd}",
  "rf|o|ntela": "\u{e8fe}",
  "rf|o|ani": "\u{e8ff}",
  "w|o|enu": "\u{e918}",
  "w|o|ntela": "\u{e919}",
  "w|o|ani": "\u{e91a}",
  "wgh|o|enu": "\u{e933}",
  "wgh|o|ntela": "\u{e934}",
  "wgh|o|ani": "\u{e935}",
  "nyn|o|enu": "\u{e94e}",
  "nyn|o|ntela": "\u{e94f}",
  "nyn|o|ani": "\u{e950}",
  "nwn|o|enu": "\u{e969}",
  "nwn|o|ntela": "\u{e96a}",
  "nwn|o|ani": "\u{e96b}",
  "nw|u|enu": "\u{e518}",
  "nw|u|ntela": "\u{e519}",
  "nw|u|ani": "\u{e51a}",
  "gb|u|enu": "\u{e533}",
  "gb|u|ntela": "\u{e534}",
  "gb|u|ani": "\u{e535}",
  "kp|u|enu": "\u{e54e}",
  "kp|u|ntela": "\u{e54f}",
  "kp|u|ani": "\u{e550}",
  "b|u|enu": "\u{e569}",
  "b|u|ntela": "\u{e56a}",
  "b|u|ani": "\u{e56b}",
  "p|u|enu": "\u{e584}",
  "p|u|ntela": "\u{e585}",
  "p|u|ani": "\u{e586}",
  "ny|u|enu": "\u{e59f}",
  "ny|u|ntela": "\u{e5a0}",
  "ny|u|ani": "\u{e5a1}",
  "m|u|enu": "\u{e5ba}",
  "m|u|ntela": "\u{e5bb}",
  "m|u|ani": "\u{e5bc}",
  "gv|u|enu": "\u{e5d6}",
  "gv|u|ntela": "\u{e5d7}",
  "gv|u|ani": "\u{e5d8}",
  "g|u|enu": "\u{e5f1}",
  "g|u|ntela": "\u{e5f2}",
  "g|u|ani": "\u{e5f3}",
  "nly|u|enu": "\u{e60c}",
  "nly|u|ntela": "\u{e60d}",
  "nly|u|ani": "\u{e60e}",
  "gw|u|enu": "\u{e627}",
  "gw|u|ntela": "\u{e628}",
  "gw|u|ani": "\u{e629}",
  "k|u|enu": "\u{e642}",
  "k|u|ntela": "\u{e643}",
  "k|u|ani": "\u{e644}",
  "kw|u|enu": "\u{e65d}",
  "kw|u|ntela": "\u{e65e}",
  "kw|u|ani": "\u{e65f}",
  "n|u|enu": "\u{e678}",
  "n|u|ntela": "\u{e679}",
  "n|u|ani": "\u{e67a}",
  "rh|u|enu": "\u{e693}",
  "rh|u|ntela": "\u{e694}",
  "rh|u|ani": "\u{e695}",
  "d|u|enu": "\u{e6ae}",
  "d|u|ntela": "\u{e6af}",
  "d|u|ani": "\u{e6b0}",
  "lr|u|enu": "\u{e6c9}",
  "lr|u|ntela": "\u{e6ca}",
  "lr|u|ani": "\u{e6cb}",
  "yh|u|enu": "\u{e6e4}",
  "yh|u|ntela": "\u{e6e5}",
  "yh|u|ani": "\u{e6e6}",
  "r|u|enu": "\u{e6ff}",
  "r|u|ntela": "\u{e700}",
  "r|u|ani": "\u{e701}",
  "y|u|enu": "\u{e71a}",
  "y|u|ntela": "\u{e71b}",
  "y|u|ani": "\u{e71c}",
  "l|u|enu": "\u{e735}",
  "l|u|ntela": "\u{e736}",
  "l|u|ani": "\u{e737}",
  "fhsh|u|enu": "\u{e750}",
  "fhsh|u|ntela": "\u{e751}",
  "fhsh|u|ani": "\u{e752}",
  "ch|u|enu": "\u{e76b}",
  "ch|u|ntela": "\u{e76c}",
  "ch|u|ani": "\u{e76d}",
  "rsh|u|enu": "\u{e786}",
  "rsh|u|ntela": "\u{e787}",
  "rsh|u|ani": "\u{e788}",
  "jz|u|enu": "\u{e7a1}",
  "jz|u|ntela": "\u{e7a2}",
  "jz|u|ani": "\u{e7a3}",
  "ssh|u|enu": "\u{e7bc}",
  "ssh|u|ntela": "\u{e7bd}",
  "ssh|u|ani": "\u{e7be}",
  "j|u|enu": "\u{e7d7}",
  "j|u|ntela": "\u{e7d8}",
  "j|u|ani": "\u{e7d9}",
  "bv|u|enu": "\u{e7f2}",
  "bv|u|ntela": "\u{e7f3}",
  "bv|u|ani": "\u{e7f4}",
  "s|u|enu": "\u{e80d}",
  "s|u|ntela": "\u{e80e}",
  "s|u|ani": "\u{e80f}",
  "t|u|enu": "\u{e828}",
  "t|u|ntela": "\u{e829}",
  "t|u|ani": "\u{e82a}",
  "fp|u|enu": "\u{e843}",
  "fp|u|ntela": "\u{e844}",
  "fp|u|ani": "\u{e845}",
  "f|u|enu": "\u{e85e}",
  "f|u|ntela": "\u{e85f}",
  "f|u|ani": "\u{e860}",
  "z|u|enu": "\u{e879}",
  "z|u|ntela": "\u{e87a}",
  "z|u|ani": "\u{e87b}",
  "bw|u|enu": "\u{e894}",
  "bw|u|ntela": "\u{e895}",
  "bw|u|ani": "\u{e896}",
  "st|u|enu": "\u{e8af}",
  "st|u|ntela": "\u{e8b0}",
  "st|u|ani": "\u{e8b1}",
  "fv|u|enu": "\u{e8ca}",
  "fv|u|ntela": "\u{e8cb}",
  "fv|u|ani": "\u{e8cc}",
  "ygh|u|enu": "\u{e8e5}",
  "ygh|u|ntela": "\u{e8e6}",
  "ygh|u|ani": "\u{e8e7}",
  "rf|u|enu": "\u{e900}",
  "rf|u|ntela": "\u{e901}",
  "rf|u|ani": "\u{e902}",
  "w|u|enu": "\u{e91b}",
  "w|u|ntela": "\u{e91c}",
  "w|u|ani": "\u{e91d}",
  "wgh|u|enu": "\u{e936}",
  "wgh|u|ntela": "\u{e937}",
  "wgh|u|ani": "\u{e938}",
  "nyn|u|enu": "\u{e951}",
  "nyn|u|ntela": "\u{e952}",
  "nyn|u|ani": "\u{e953}",
  "nwn|u|enu": "\u{e96c}",
  "nwn|u|ntela": "\u{e96d}",
  "nwn|u|ani": "\u{e96e}",
};

export const ndebeModules = [
  { number: 0, title: "Check and setup", detail: "Confirm the font and choose an input method.", status: "current" },
  { number: 1, title: "Thinking in syllables", detail: "Move from letters to one character per syllable.", status: "open" },
  { number: 2, title: "Vowels", detail: "Recognise the vowel set and syllabic N/M.", status: "open" },
  { number: 3, title: "Tones", detail: "See how high, mid, and low tone shape a character.", status: "open" },
  { number: 4, title: "Stems", detail: "Explore the stem grid and shared Latin readings.", status: "open" },
  { number: 5, title: "How a character grows", detail: "Build with a stem, fruit radical, vowel, and branch.", status: "open" },
  { number: 6, title: "Build your first syllable", detail: "Choose a stem, vowel, and tone in order.", status: "open" },
  { number: 7, title: "Numerals", detail: "Twenty digits made of a flag and a body.", status: "open" },
  { number: 8, title: "Arithmetic", detail: "Base 20 place value, comparing, promotion and demotion.", status: "open" },
] as const;

// Stem keyboard layout (6 rows × 7) as shown on typendebe.com.
export const ndebeStemRows = [
  ["nw", "gb", "kp", "b", "p", "ny", "m"],
  ["gv", "g", "nly", "gw", "k", "kw", "n"],
  ["rh", "d", "lr", "yh", "r", "y", "l"],
  ["fhsh", "ch", "rsh", "jz", "ssh", "j", "bv"],
  ["s", "t", "fp", "f", "z", "bw", "st"],
  ["fv", "ygh", "rf", "w", "wgh", "nyn", "nwn"],
] as const;
export const ndebeStems = ndebeStemRows.flat();

export const ndebeVowels = ["a", "e", "i", "o", "u"] as const;
export const ndebeTones = ["High", "Mid", "Low"] as const;

export const ndebeParts = [
  { name: "Stem", description: "The tall main consonant form. Teaching shape: a tall rectangle." },
  { name: "Fruit radical", description: "A small component beside the stem. Teaching shape: a small square." },
  { name: "Vowel", description: "The vowel form placed above; its shape carries the tone. Teaching shape: a horizontal rectangle." },
  { name: "Connecting branch", description: "Required whenever a vowel or vowel placeholder sits above the body." },
  { name: "Nzobe", description: "Gives the surviving vowel an elision form, showing it hides an earlier vowel." },
] as const;

// Teaching-form component names from ndebe.org/script/teaching.
export const teachingStems = ["nkuo", "duu", "ukwu", "dogo", "ukwuna", "bo", "iyi"] as const;
export const teachingRadicals = ["nkoakpu", "ome-nkuo", "sisi", "amu", "mamkpulu", "ome-obe"] as const;
export const teachingVowelBases = ["a", "e-dot", "i-dot", "o-dot", "u-dot", "e", "i", "o", "u"] as const;
export const teachingVowelTones = [
  { id: "enu", label: "High (enu)" },
  { id: "ntela", label: "Mid (ntela)" },
  { id: "ani", label: "Low (ani)" },
] as const;

// Catalogue sample: stem combining components with private-use code points.
const combNames = ["nw", "gb", "kp", "b", "p", "ny", "m", "gv", "g", "nly", "gw", "k", "kw", "n", "rh", "d", "lr", "yh", "r", "y", "l", "fhsh", "ch", "rsh", "jz", "ssh", "j", "bv", "s", "t"];
export type CatalogueCategory = "Syllables" | "Nzobe" | "Components" | "Numerals" | "Symbols" | "Teaching" | "Support";
export const catalogueCategories: ("All" | CatalogueCategory)[] = ["All", "Syllables", "Nzobe", "Components", "Numerals", "Symbols", "Teaching", "Support"];
export type CatalogueGlyph = { name: string; code: string | null; category: CatalogueCategory };

export const ndebeNumeralNames = ["ncha", "ofu", "ibuo", "ito", "ino", "ise", "isi", "isa", "isato", "isano", "ili", "mofu", "mibuo", "mito", "mino", "mise", "misi", "misa", "misato", "misano"] as const;

export const catalogueGlyphs: CatalogueGlyph[] = [
  ...combNames.map((name, i) => ({ name: `${name}.comb`, code: `U+${(0xe450 + i).toString(16).toUpperCase()}`, category: "Components" as const })),
  ...ndebeNumeralNames.map((name, i) => ({ name: `digit.${i} · ${name}`, code: null, category: "Numerals" as const })),
  { name: "okoloto.ise (flag 5)", code: null, category: "Numerals" },
  { name: "okoloto.ili (flag 10)", code: null, category: "Numerals" },
  { name: "okoloto.mise (flag 15)", code: null, category: "Numerals" },
  { name: "interpunct · word separator", code: null, category: "Symbols" },
  { name: "vigesimal marker", code: null, category: "Symbols" },
  { name: "decimal marker", code: null, category: "Symbols" },
  { name: "kobo sign ƙ", code: "U+0199", category: "Symbols" },
  { name: "naira sign ₦", code: "U+20A6", category: "Symbols" },
  { name: "dotted circle · stem placeholder", code: "U+25CC", category: "Teaching" },
  { name: "radical placeholder", code: null, category: "Teaching" },
  { name: "vowel placeholder", code: null, category: "Teaching" },
  { name: "nzobe", code: null, category: "Nzobe" },
  { name: "replacement character", code: "U+FFFD", category: "Support" },
  { name: "nonbreaking space", code: "U+00A0", category: "Support" },
  { name: "narrow nonbreaking space", code: "U+202F", category: "Support" },
  { name: "space", code: "U+0020", category: "Support" },
];
export const catalogueTotal = 6709;

export const typingShortcuts = [
  { keys: "Space", action: "Ordinary space" },
  { keys: "Shift + Space", action: "Interpunct / word separator" },
  { keys: "` (backtick)", action: "Nzobe: type after the stem and radical, before the surviving vowel" },
  { keys: "' / Shift + '", action: "Alternating single / double outward-prong quotations" },
  { keys: "0 – 9", action: "Ndebe digits 0–9" },
  { keys: "Option/Alt + 0 – 9", action: "Ndebe digits 10–19" },
  { keys: ". after a numeral", action: "Vigesimal marker: two low stacked dots" },
  { keys: ". elsewhere", action: "Full stop" },
  { keys: "Option/Alt + .", action: "Decimal marker: one low dot" },
  { keys: "Option/Alt + Shift + .", action: "Explicit full stop after a number" },
] as const;

export const typingNotes = [
  { title: "Palettes", body: "Math, Currency, Teaching, and Symbols and spacing have separate labelled buttons. Keyboard users reach them with Tab, then Enter or Space." },
  { title: "Quotation direction", body: "Quotation direction is inferred from the text before the caret. Keyman checks up to 64 preceding characters." },
  { title: "Saved text", body: "Saving exports plain UTF-8 text. Plain text keeps characters only: choose an Ndebe font again if reopened text shows missing-character boxes." },
  { title: "Support characters", body: "The dotted rectangle provides a teaching stem placeholder. Nonbreaking spaces keep adjacent text together without a visible mark." },
] as const;

export const palettes = {
  Currency: ["₦", "ƙ", "$", "£", "€", "¥", "₩"],
  "Symbols and spacing": ["@", "#", "&", "_", "*", "^", "~", ":", "…", "—", "–", "«", "»", "‹", "›", "\u00A0", "\u202F"],
  Math: ["+", "−", "×", "÷", "=", "≠", "<", ">", "≤", "≥", "±", "≈", "∶", "%", "‰", "/", "\\", "|", "°", "℃", "℉", "←", "→", "↔", "π", "√", "∛", "∞", "[", "]", "{", "}"],
  Teaching: ["◌", "[radical ◌]", "[vowel ◌]"],
} as const;

export const ndebeFonts = [
  { name: "Ńdẹ́bẹ́ Rounded", tagline: "A lighter hand.", weight: 400, href: "https://ndebe.org/script/NdebeRounded-Regular.ttf" },
  { name: "Ńdẹ́bẹ́ Soft Bold", tagline: "A fuller presence.", weight: 700, href: "https://ndebe.org/script/NdebeSoftBold-Regular.ttf" },
] as const;
export const keymanPackage = "https://ndebe.org/script/ndebe_2026.kmp";
export const fontsRepo = "https://github.com/ndebeproject/ndebe-fonts";

export const arithmeticRules = [
  { title: "Flag promotion", trigger: "Body reaches 5B or more", effect: "Advance one flag level and subtract 5 from the body", example: "0F + 7B → 5F + 2B" },
  { title: "Flag demotion", trigger: "Body subtraction is impossible", effect: "Drop one flag level and add 5 to the body", example: "10F 2B − 4B → 5F 7B − 4B → 5F 3B" },
  { title: "Place promotion", trigger: "Flags would reach 20F", effect: "Carry 1B to the next place; flags reset to 0F", example: "15 + 7 → 1 in twenties, 0F2B in units = 22" },
  { title: "Place demotion", trigger: "Current place is too small", effect: "1B from the place above becomes 15F0B + 5F0B here", example: "1 twenty → 15F0B + 5F0B units" },
] as const;

export const operationSummary = [
  { op: "Compare", method: "More digits wins; else leftmost digit, flag first, then body", rule: "A flag step (5) always outweighs any body (≤ 4)" },
  { op: "Addition", method: "Flags + flags, bodies + bodies", rule: "Flag promote when body ≥ 5; place promote at 20F" },
  { op: "Subtraction", method: "Flags − flags, bodies − bodies", rule: "Flag demote when body too small; place demote when flags run out" },
  { op: "Multiplication", method: "Core fact table; ×5 is a rotation; ×20 is a shift", rule: "Partial products shifted by place, then added" },
  { op: "Division", method: "Short division by flag card, or a 7-rung ladder", rule: "Largest flag rung first, then largest body rung" },
  { op: "Fractions", method: "Place value continues below the units", rule: "Round up when the next digit shows a 10F/15F flag" },
] as const;

export const placeValues = ["Units", "Twenties", "Four-hundreds", "Eight-thousands", "Hundred-and-sixty-thousands", "Three-million-two-hundred-thousands"] as const;

export function toBase20(n: number): number[] {
  if (!Number.isFinite(n) || n <= 0) return [0];
  const digits: number[] = [];
  let v = Math.floor(n);
  while (v > 0) { digits.unshift(v % 20); v = Math.floor(v / 20); }
  return digits;
}
export const flagOf = (d: number) => Math.floor(d / 5) * 5;
export const bodyOf = (d: number) => d % 5;
export const numeralNotation = (d: number) => `${flagOf(d)}F${bodyOf(d)}B`;
